public enum COURSECODES {
    ACCT,AGR,ANSC,ANTH,ARTH,ASCI,BIOC,BIOL,BIOM,BOT,CHEM,CHIN,CLAS,
    CIS,COOP,CROP,ECON,ECRD,ENGG,ENGL,ENVS,ENVB,ENVM,EQN,EURO,XSEN,FRHD,
    FARE,FOOD,FREN,GEOG,GEOL,GERM,GREK,HIST,HORT,HTM,HROB,HK,HUMN,IPS,ISS,
    UNIV,IBIO,IDEV,ITAL,LARC,LAT,LING,MGMT,MCS,MATH,MICR,MCB,MBG,MUSC,
    NANO,NEUR,NUTR,OAGR,PATH,PHIL,PHYS,PBIO,POLS,POPM,PORT,PSYC,REAL,
    SOC,SOAN,SPAN,STAT,SART,THST,TOX,VETM,WMST,ZOO
}
