public enum SCIENCECODES {

       AGR,ANSC,BIOC,BIOL,BIOM,BOT,CHEM,CIS,CROP,ECON,ENGG,ENVS,ENVB,ENVM,EQN,
        FARE,FOOD,GEOL,HORT,HK,MATH,MICR,MCB,MBG,NANO,NEUR,NUTR,PATH,PHYS,PBIO,POPM,PORT,PSYC,
        SOIL,STAT,TOX,ZOO

}
